
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: extractiq-backend
    container_name: extractiq-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: extractiq-frontend
    container_name: extractiq-frontend
    ports:
      - "80:80"
    depends_on:
      - backend